language: rust

matrix:
  include:
    - os: linux
      # Oldest supported version.
      rust: 1.25.0

    - os: linux
      # Oldest version shipped by Debian at the time of writing.
      rust: 1.34.2

    - os: linux
      # Latest version at the time of writing.
      rust: 1.50.0

    - os: linux
      rust: beta

    - os: linux
      rust: nightly

    - os: osx
      rust: stable

    - os: osx
      rust: beta

    - os: osx
      rust: nightly
